#if !canImport(ObjectiveC)
import XCTest

extension LinguisticKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LinguisticKitTests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

extension ScriptTableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScriptTableTests = [
        ("testEscaping", testEscaping),
        ("testRuScriptTable", testRuScriptTable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LinguisticKitTests.__allTests__LinguisticKitTests),
        testCase(ScriptTableTests.__allTests__ScriptTableTests),
    ]
}
#endif
